#!/usr/bin/env bash

APPDIR="$(dirname -- "$(readlink -f -- "${0}")" )"

sed -i "/sketchbook.path=/c\sketchbook.path=$APPDIR/sketchbook"  $APPDIR/preferences.txt
$APPDIR/arduino  --preferences-file $APPDIR/preferences.txt

